// Code generated by mockery v2.30.1. DO NOT EDIT.

package updateclassesdone_test

import (
	gin "github.com/gin-gonic/gin"
	command "github.com/julianVelandia/EDteam/DDDyCQRS/internal/student/application/command"

	mock "github.com/stretchr/testify/mock"
)

// MapperMock is an autogenerated mock type for the Mapper type
type MapperMock struct {
	mock.Mock
}

// RequestToCommand provides a mock function with given fields: ctx
func (_m *MapperMock) RequestToCommand(ctx *gin.Context) command.UpdateClassesDone {
	ret := _m.Called(ctx)

	var r0 command.UpdateClassesDone
	if rf, ok := ret.Get(0).(func(*gin.Context) command.UpdateClassesDone); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(command.UpdateClassesDone)
	}

	return r0
}

// NewMapperMock creates a new instance of MapperMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMapperMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MapperMock {
	mock := &MapperMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
