// Code generated by mockery v2.30.1. DO NOT EDIT.

package updateclassesdone_test

import (
	command "github.com/julianVelandia/EDteam/DDDyCQRS/internal/student/application/command"
	mock "github.com/stretchr/testify/mock"
)

// UseCaseMock is an autogenerated mock type for the UseCase type
type UseCaseMock struct {
	mock.Mock
}

// Execute provides a mock function with given fields: cmd
func (_m *UseCaseMock) Execute(cmd command.UpdateClassesDone) error {
	ret := _m.Called(cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(command.UpdateClassesDone) error); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUseCaseMock creates a new instance of UseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCaseMock {
	mock := &UseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
