// Code generated by mockery v2.30.1. DO NOT EDIT.

package usecase_test

import (
	domain "github.com/julianVelandia/EDteam/DDDyCQRS/internal/student/domain"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryViewProfileMock is an autogenerated mock type for the RepositoryViewProfile type
type RepositoryViewProfileMock struct {
	mock.Mock
}

// GetProfileByEmail provides a mock function with given fields: email
func (_m *RepositoryViewProfileMock) GetProfileByEmail(email string) (domain.Profile, []domain.Class, error) {
	ret := _m.Called(email)

	var r0 domain.Profile
	var r1 []domain.Class
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (domain.Profile, []domain.Class, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) domain.Profile); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(domain.Profile)
	}

	if rf, ok := ret.Get(1).(func(string) []domain.Class); ok {
		r1 = rf(email)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]domain.Class)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewRepositoryViewProfileMock creates a new instance of RepositoryViewProfileMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryViewProfileMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryViewProfileMock {
	mock := &RepositoryViewProfileMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
